Once-Upon/context

src/heuristics/erc1155Purchase.ts
src/heuristics/erc1155Sale.ts
src/heuristics/erc721Purchase.ts
src/heuristics/erc721Sale.ts

Handle undefined values better

---

README.md
src/commands/createContextualizer.ts
src/commands/grabTransaction.ts
src/commands/utils.ts
src/template/contextualizer.spec.template.hbs

When you run create contextualization with a new optional tx

---

src/protocol/ens/registrar.spec.ts
src/protocol/ens/reverse.spec.ts
src/protocol/superchainFaucet.spec.ts
src/protocol/weth.spec.ts

Add failing test for protocol contextualizers

---

package.json

Includes https://github.com/Once-Upon/context/pull/58

Bump version to 25

---

package-lock.json
package.json

Includes https://github.com/Once-Upon/context/pull/46

Bump version to 26

---

package-lock.json
package.json

Includes https://github.com/Once-Upon/context/pull/62

Bump version to 27

---

package-lock.json
package.json

Includes:
https://github.com/Once-Upon/context/pull/68
https://github.com/Once-Upon/context/pull/64

Bump version to 28

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/74

Bump version to 30

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/60
* https://github.com/Once-Upon/context/pull/80
* https://github.com/Once-Upon/context/pull/73

Bump version to 31

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/85

Bump version to 33

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/91
* https://github.com/Once-Upon/context/pull/93
* and smaller PRs that aren't relevant at a high level

Bump version to 36

---

src/commands/runContextualizers.ts
src/helpers/utils.ts

Just a few small type-related improvements to `runContextualizers` and `helpers/utils`

Type fixes

---

src/commands/runContextualizers.ts
src/contextualizer.spec.ts
src/heuristics/index.ts

Behavior tests to run all contextualizers and see which

---

package.json

Includes:
* https://github.com/Once-Upon/context/pull/113

Bump version to 38

---

src/heuristics/erc1155Purchase/erc1155Purchase.ts
src/heuristics/erc1155Sale/erc1155Sale.ts
src/heuristics/erc721Purchase/erc721Purchase.ts
src/heuristics/erc721Sale/erc721Sale.ts
src/heuristics/idm/idm.ts
src/heuristics/tokenAirdrop/tokenAirdrop.ts
src/protocol/eas/eas.ts
src/protocol/eas/schemaRegistry.ts
src/protocol/ens/registrar.ts
src/protocol/ens/reverse.ts
src/protocol/farcaster/storageRegistry.ts
src/types/transaction.ts

Add an indexed field to variables in contextualizations

---

package.json

Includes:
* https://github.com/Once-Upon/context/pull/115

Bump version to 39

---

package.json

Includes:
* https://github.com/Once-Upon/context/pull/116

Bump version to 40

---

package.json

Includes:
* https://github.com/Once-Upon/context/pull/119

Bump version to 41

---

src/protocol/eas/constants.ts
src/protocol/eas/eas.ts
src/protocol/eas/schemaRegistry.ts

Build EAS links for other networks

---

package.json

Includes:
* https://github.com/Once-Upon/context/pull/121

Bump version to 42

---

package.json

Includes:
* https://github.com/Once-Upon/context/pull/123

Bump version to 43

---

package.json

Includes:
* https://github.com/Once-Upon/context/pull/125

Bump version to 44

---

src/protocol/eas/schemaRegistry.ts
src/types/transaction.ts

Resolves OU-1379
Resolves OU-1365

Add schema code variable for EAS registrations

---

package.json

Includes:
* https://github.com/Once-Upon/context/pull/130

Bump version to 45

---

package.json

Includes:
* https://github.com/Once-Upon/context/pull/134

Bump verison to 46

---

package.json

Includes:
* https://github.com/Once-Upon/context/pull/143
* https://github.com/Once-Upon/context/pull/141
* https://github.com/Once-Upon/context/pull/140
* https://github.com/Once-Upon/context/pull/139
* https://github.com/Once-Upon/context/pull/136
* https://github.com/Once-Upon/context/pull/128
* https://github.com/Once-Upon/context/pull/129

Bump version to 47

---

package.json

Includes:
* https://github.com/Once-Upon/context/pull/147
* https://github.com/Once-Upon/context/pull/145

Bump version to 48

---

package.json

Includes:
* https://github.com/Once-Upon/context/pull/149

Bump version to 49

---

package.json

Includes:
* https://github.com/Once-Upon/context/pull/142

Bump version to 50

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/135

Bump version to 51

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/162
* https://github.com/Once-Upon/context/pull/160
* https://github.com/Once-Upon/context/pull/156
* https://github.com/Once-Upon/context/pull/155

Bump version to 53

---

src/helpers/utils.ts
src/protocol/eas/constants.ts
src/protocol/eas/eas.spec.ts
src/protocol/eas/eas.ts
src/protocol/eas/schemaRegistry.ts
src/types/context.ts

Use EAS uid instead of schema

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/167

Bump version to 54

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/170

Bump version to 55

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/146
* https://github.com/Once-Upon/context/pull/166
* https://github.com/Once-Upon/context/pull/163

Bump version to 56

---

src/protocol/nouns/auctionHouse.spec.ts
src/protocol/nouns/auctionHouse.ts
src/protocol/nouns/daoLogic.spec.ts
src/protocol/nouns/daoLogic.ts
src/protocol/nounsBuilder/auction.ts
src/protocol/nounsBuilder/governor.ts

Related:
* https://github.com/Once-Upon/context/pull/161
Resolves OU-1525
Note: There are two remaining test failures blocking a merge of this PR

Fix undefined errors in Nouns PR

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/161

Bump version to 57

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/175

Bump version to 58

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/177

Bump version to 59

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/181
* https://github.com/Once-Upon/context/pull/179

Bump version to 60

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/185
* https://github.com/Once-Upon/context/pull/186

Bump version to 62

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/188

Bump version to 63

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/190

Bump version to 64

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/194

Bump version to 65

---

src/heuristics/erc1155Mint/erc1155Mint.spec.ts
src/heuristics/erc1155Mint/erc1155Mint.ts
src/heuristics/erc721Mint/erc721Mint.spec.ts
src/heuristics/erc721Mint/erc721Mint.ts
src/test/transactions/erc1155MintBySomeoneElse-0xa9ddcb75.json

Drop the final NFT mint rule

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/196

Bump version to 66

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/198

Bump version to 67

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/200

Bump version to 68

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/202

Bump version to 69

---

src/protocol/nounsBuilder/auction.ts
src/protocol/nounsBuilder/governor.ts

TODO: Update tests and make this change in the other Nouns Builder file too

Use Nouns Builder title

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/192
* https://github.com/Once-Upon/context/pull/205

Bump version to 70

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/207
* https://github.com/Once-Upon/context/pull/204

Bump version to 71

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/210
* https://github.com/Once-Upon/context/pull/209

Bump version to 72

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/223
* https://github.com/Once-Upon/context/pull/222

Bump version to 73

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/227

Bump version to 74

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/230

Bump version to 75

---

package-lock.json
package.json

@ponyjackal @jordanmessina @cdt-eth It's nice that the 77 version lined up with Zora support 😁
Includes:
* https://github.com/Once-Upon/context/pull/235

Bump version to 77

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/239

Bump version to 79

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/241

Bump version to 80

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/243

Bump version to 81

---

src/protocol/zoraCreator/zoraCreator.spec.ts
src/protocol/zoraCreator/zoraCreator.ts
src/test/transactions/zoraMintWithRewards-0x837a9a69.json

Decide how we want to handle zora mints like this one that

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/246

Bump version to 82

---

src/types/transaction.ts

Related to https://github.com/Once-Upon/context/pull/253, but this one is shippable sooner.

Add new value to tx type

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/254

Bump version to 83

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/252

Bump version to 84

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/261

Bump version to 85

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/256

Bump version to 86

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/267

1.0.0-6 with usability

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/270

Bump version to 88

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/273

Bump version to 90

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/282

Prerelease 1.0.0-9

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/288

Bump version to 1.0.2

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/293

Release 1.0.5 w/ Highlight creator rewards for mints

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/299

Bump version to 1.0.6

---

package-lock.json
package.json
src/commands/grabTransaction.ts
src/contextualizers/protocol/highlight/highlight.spec.ts
src/contextualizers/protocol/highlight/highlight.ts
src/contextualizers/test/transactions/highlightErc20-0x1f0c411b.json

Handle ERC20s for Highlight

---

package-lock.json
package.json
src/contextualizers/heuristics/erc1155Mint/erc1155Mint.spec.ts
src/contextualizers/heuristics/erc1155Mint/erc1155Mint.ts
src/contextualizers/heuristics/erc20Mint/erc20Mint.ts
src/contextualizers/heuristics/erc721Mint/erc721Mint.ts
src/contextualizers/test/transactions/erc1155MintPaidWithEnjoy-0x7a3686d7.json

Release 1.0.8: Detect mints when paying with non-ETH tokens

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/294

Bump version to 1.0.10

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/313

Bump version to 1.0.12

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/315

Bump version to 1.0.13

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/317

Bump version to 1.0.14

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/321

Bump version to 1.0.15

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/320

Bump version to 1.0.16

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/291

Bump version to 1.0.17

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/326

Bump version to 1.0.18

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/328

Bump version to 1.0.19

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/330

Bump version to 1.0.20

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/332

Bump version to 1.0.21

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/334

Bump version to 1.0.22

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/319

Bump version to 1.0.23

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/337

Bump version to 1.0.24

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/341

Bump version to 1.0.26

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/344

Bump version to 1.0.27

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/346

Bump version to 1.0.28

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/350

Bump version to 1.0.31

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/352

Bump version to 1.0.32

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/355
* https://github.com/Once-Upon/context/pull/343
* https://github.com/Once-Upon/context/pull/354

Bump version to 1.0.33

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/357

Bump version to 1.0.34

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/362
* https://github.com/Once-Upon/context/pull/363

Bump version to 1.0.35

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/365
* https://github.com/Once-Upon/context/pull/364

Bump version to 1.0.36

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/369
* https://github.com/Once-Upon/context/pull/371

Bump version to 1.0.37

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/375

Bump version to 1.0.38

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/374

Bump version to 1.0.39

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/378

Bump version to 1.0.40

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/392

1.1 actions cleanup

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/395

Bump version to 1.0.42

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/397

Bump version to 1.0.43

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/400

Bump version to 1.0.45

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/401

Bump version to 1.0.46

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/408

Bump version to 1.0.47

---

src/contextualizers/protocol/nouns/index.ts

Related:
* https://github.com/Once-Upon/context/pull/408

Run new contextualizer

---

package-lock.json
package.json

Includes:
* https://github.com/Once-Upon/context/pull/410

Bump version to 1.0.48
